### ISSUE TITLE
Not having at least empty opts = {} in the blink.cmp -> sources ->providers -> ripgrep = {} leads to callback issues about opts being nil

### ISSUE THREAD

**Issue by rsniezek** [mikavilpas/blink-ripgrep.nvim#52]
Hi,

First of all, thanks for great work. I just wanted to let you know that if I don't include at least an empty opts = {} in my sources = { providres = { ripgrep  = {}}}, I'm getting a callback error on each key press in neovim, about
"attempt to index local opts (a nil value)". issue disappears as soon as I add opts = {} there. I think it's worth at least mentioning in the readme, currenlty it suggets that the options are optional and while the options themselves might be, the entire object (? not sure about lua nomenclature) is not.

Below is piece of my config that causes the issue, uncommenting the line fixes it.

```lua require("blink.cmp").setup({
  sources = {
    providers = {
      ripgrep = {
        module = "blink-ripgrep",
        name = "Ripgrep",
        enabled = true,
--        opts = {},
      },
    },
    completion = {
      enabled_providers = { "lsp", "path", "buffer", "ripgrep" },
    },
  },
})
```

**Comment by mikavilpas** [comment]
Oh, I wasn't aware of this. Thanks for letting me know.

I'll check it out later, I'm a bit busy right now 🙂

**Comment by mikavilpas** [comment]
Ok, this should now be fixed. Please reopen if you continue to see the issue 👍🏻
