### ISSUE TITLE
Option to remove (rg) from the title

### ISSUE THREAD

**Issue by daniel-for-mp** [mikavilpas/blink-ripgrep.nvim#64]
I already append source_names in my blink.cmp config, could we add an option to remove the source from the completion item?

**Comment by mikavilpas** [comment]
Ah sounds like a nice idea. I think I'll add an option to customize this!

**Comment by mikavilpas** [comment]
Can you show me an example of how you do this? I couldn't easily figure this out, but it sounds like something I would also like to have.

**Comment by mikavilpas** [comment]
Meanwhile you can customize the items in your own config - follow this example:

https://github.com/mikavilpas/blink-ripgrep.nvim/issues/60#issuecomment-2557613395

**Comment by mikavilpas** [comment]
Thanks for the suggestion - I just removed "(rg)" by default. It's much better to add it manually if needed, I think 👍🏻
