### ISSUE TITLE
RG should consider the order when determine root directory

### ISSUE THREAD

**Issue by Kaiser-Yang** [mikavilpas/blink-ripgrep.nvim#73]
When I use this configuration, I hope it first to check if there is a directory named `.root`, then `.git`, last use current directory as root directory.

```lua
project_root_marker = { '.root', '.git', '.' }
```

But when I use this configuration, `RG` use `.` as root directory, even though there is a `.git` at its ancestor.

**Comment by mikavilpas** [comment]
I guess that's not how it works. Does it fallback to nvim's cwd if you leave out . ?

It also allows for full customization if you pass in a function. Does this work?

**Comment by Kaiser-Yang** [comment]
Oh, just remove the `'.'` will work as expected, I found that in the source code, when the root is not found, use `get_cwd` as root.

**Comment by mikavilpas** [comment]
That's great - thanks for confirming. I could add something about this to the readme so it's a bit more clear.
